# Generated by Django 2.2.6 on 2020-03-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200323_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
    ]
