# Generated by Django 2.2.6 on 2020-03-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userposts_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userposts',
            options={'verbose_name_plural': 'UserPosts'},
        ),
    ]
