# Generated by Django 2.2.6 on 2020-03-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200323_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='img',
            field=models.ImageField(blank=True, upload_to='blog_image'),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='post_choice',
            field=models.CharField(choices=[('PUB', 'Public'), ('PRI', 'Private')], default='Public', max_length=5),
        ),
    ]
