# Generated by Django 2.2.6 on 2020-03-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200323_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='post_choice',
            field=models.CharField(default='Public', max_length=10),
        ),
    ]
