# Generated by Django 2.2.6 on 2020-03-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200323_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='task2/media/blog_image'),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='title',
            field=models.CharField(default='No_post', max_length=200),
        ),
    ]
