# Generated by Django 2.2.6 on 2020-03-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200323_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='post_choice',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=8),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
    ]
